### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by kuujakke** [impliedfeline/JuiSynth#1]
Koodi ladattu ja arvioitu 31.12.2016 noin Klo. 15.00

- Mainin kommentit hyvin kattavia ja selkeyttää ohjelman toimintaa.
- Luokkakaavio luettavissa ja suhteellisen selkeä ilman syvempää tutustumista aiheeseen.
- Koodi kääntyi ilman suurempia ongelmia ja varoitus kovasta äänestä oli paikallaan.
- Oskillaattori on kovin suuri luokka ja sen voisi pilkkoa pienempiin osiin joka selkeyttäisi sen toimintaa.
- Ehdottaisinkin esimerkiksi jonkinlaista Factorya näytteen generointiin.

Hienoa.

**Comment by impliedfeline** [comment]
Kiitokset palautteesta!
