### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by hanninev** [impliedfeline/JuiSynth#2]
Koodi ladattu 8.1. klo 19.30.

- Luokkakaavio on selkeä. Siitä ja aiheenkuvauksesta sai hyvän kuvan ohjelman toiminnasta.
- Testit ovat hyviä ja ne menevät läpi. Logiikan rivikattavuus jää kuitenkin jonkin verran alhaisemmaksi kuin on tavoitteena, joten testejä voisi tehdä lisää.
- Koodi on siistiä ja luokkien vastuut on jaettu selkeästi. Ainoastaan Oscillator-luokka on hieman pitkä, joten voisi miettiä, olisiko sitä syytä jakaa pienemmiksi luokiksi. Toisaalta suurin osa luokan koodista on vain settereitä ja gettereitä.
- Metodit, luokat ja muuttujat on nimetty kuvaavasti. Myös Javadoc ja kommentit selkeyttävät ohjelmaa.
- Käyttöliittymässä ei ollut vielä lainkaan toiminnallisuutta, mutta se oli rakennettu järkevästi. Käytettävyys on varmasti hyvä.

**Comment by impliedfeline** [comment]
Kiitokset palautteesta!
